name: eye_recognition
description: "Iris recognition app for person identification and data registration"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Camera
  camera: ^0.11.1

  # Local database
  sqflite: ^2.4.2
  path: ^1.9.1

  # State management
  provider: ^6.1.5

  # Image processing
  image: ^4.5.3

  # UUID generation for records
  uuid: ^4.5.1

  # Path utilities
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
